name: Check Coding Style with flake8 on Changed Lines

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.py'

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Choose the Python version you need

      - name: Install dependencies
        run: pip install flake8

      - name: Identify changed lines and files
        run: |
          python extract_changes.py ${{ github.event.before }} ${{ github.event.after }}

      - name: Run flake8 on changed lines
        run: |
          flake8 $(cat changed_files.txt)
