name: Check Coding Style with flake8 on Changed Lines

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    paths:
      - '**/*.py'

jobs:
  flake8:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11  # Choose the Python version you need

      - name: Install dependencies
        run: pip install flake8

      - name: Create a temporary branch
        run: git checkout -b temp-branch

      - name: Determine changed files and lines
        run: |
          CHANGED_FILES=$(git diff --name-only ${{ github.event.before }} ${{ github.event.after }} | xargs)
          CHANGED_LINES=$(git diff -U0 ${{ github.event.before }} ${{ github.event.after }} $CHANGED_FILES | sed -n -e '/^+[^+]/ p' | flake8 --diff --jobs=auto --diff-str $(cat))
          echo "$CHANGED_LINES" > changed_lines.txt

      - name: Run flake8 on changed lines
        run: |
          flake8 --jobs=auto --diff $(cat changed_lines.txt)
